### ISSUE TITLE
Can't add switch /epic games manually to "Here's what we found" window

### ISSUE THREAD

**Issue by bexrr** [Agreon/game-watch#156]
After adding a PS game, Switch was preselected
Try adding:
https://www.nintendo.de/Spiele/Nintendo-Switch-Spiele/Xenoblade-Chronicles-3-2168340.html
https://www.nintendo.de/Spiele/Nintendo-Switch-Spiele/Xenoblade-Chronicles-3-2168340.html#gameDetails
Select epic and try adding:
https://store.epicgames.com/en-US/p/tiny-tinas-wonderlands
-> Error window with could not add ID appears

When using "add new info source":
- works for switch
- epic still does not work

**Comment by Agreon** [comment]
Epic is not wokring at the moment
