### ISSUE TITLE
Improvement: Don't clear "name of the game" input when no game is added

### ISSUE THREAD

**Issue by bexrr** [Agreon/game-watch#180]
Clearing input when game is added is ok

**Comment by Hurhaj** [comment]
Hello , can you assign this issue to me? I really'd like to participate!

**Comment by Hurhaj** [comment]
Hello @Agreon ,  can you assign this issue to me? This improvement looks interesting and I would like to participate!

**Comment by Hurhaj** [comment]
Im done with solving this issue. Nothing was said about I should create PR. Hope its alright this way. Please let me know  when you reviewed this PR. #670 .
