### ISSUE TITLE
Add Notification for when a User score is added to a metacritic source

### ISSUE THREAD

**Issue by Agreon** [Agreon/game-watch#650]
We'll just need to add another `NotificationCreator` in the `notificator` service

**Comment by Ritish134** [comment]
Hi there excited to contribute . May you explain  in brief what to do exactly.

**Comment by Agreon** [comment]
Hey cool! Well you'll have to add a `NotificationCreator` similar to https://github.com/Agreon/game-watch/blob/main/notifier/src/notifiers/new-metacritic-rating-notification-creator.ts as well as a new `NotificationType`. For this type the frontend and the `MailService` will need new switch-case entries on how to display that kind of notification. 
I guess the easiest way to find places to add the code is to search for `NotificationType.NewMetacriticRating` and just place the new Type nearby

**Comment by Agreon** [comment]
Ah, and so far, a notificaiton is created when a `Metacritic` source entity is added. But the `userScore` of the data may be `tbd` at that point. If it will be a number, we want to create a new notification
